spring.application.name=accountservice

spring.datasource.url=jdbc:postgresql://localhost:5432/px_account_service
spring.datasource.username=ambati
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

# Swagger / OpenAPI config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY:}
spring.autoconfigure.exclude[0]=org.springframework.ai.model.google.genai.autoconfigure.chat.GoogleGenAiChatAutoConfiguration
spring.autoconfigure.exclude[1]=org.springframework.ai.model.google.genai.autoconfigure.image.GoogleGenAiImageAutoConfiguration
spring.autoconfigure.exclude[2]=org.springframework.ai.model.google.genai.autoconfigure.embedding.GoogleGenAiTextEmbeddingAutoConfiguration
spring.autoconfigure.exclude[3]=org.springframework.ai.model.google.genai.autoconfigure.embedding.GoogleGenAiEmbeddingConnectionAutoConfiguration
spring.autoconfigure.exclude[4]=org.springframework.ai.model.google.genai.autoconfigure.image.GoogleGenAiImageConnectionAutoConfiguration
spring.autoconfigure.exclude[5]=org.springframework.ai.model.anthropic.autoconfigure.AnthropicChatAutoConfiguration
